### ISSUE TITLE
Copying a big dripleaf does not correctly copy tilt

### ISSUE THREAD

**Issue by Zailer43** [Sjouwer/pick-block-pro#10]
copying a big dripleaf copies the `tilt` state as it provides but it is buggy since placing it if it is not in lowercase does not work

![2022-12-26_11-34](https://user-images.githubusercontent.com/63565983/209559394-9ac9e136-0dca-413f-b2c1-c4c106c8ddaf.png)

I don't know if this happens with other states of other blocks but it could be possible

**Comment by Sjouwer** [comment]
Thank you for the report, I did some testing and found a few more like this, it indeed looks like nbt values should always be fully lowercase to work. I'll fix this asap
