### ISSUE TITLE
One typo, one suggestion

### ISSUE THREAD

**Issue by fungoza** [Sjouwer/pick-block-pro#12]
![image](https://user-images.githubusercontent.com/68079109/210291435-fa4b9976-e5b2-43b6-8d46-36fbb5b666a9.png)
(In Creative sword enchantments)

And I recommend use default minecraft's enchantments translation keys instead mod's

**Comment by Sjouwer** [comment]
Thank you, I'll fix that soon

> And I recommend use default minecraft's enchantments translation keys instead mod's  

Sadly, as far as I know, this isn't possible with Cloth Config
Thanks for the suggestion though
