### ISSUE TITLE
Problem on copy of glow_item_frame with item

### ISSUE THREAD

**Issue by RedstoneFuture** [Sjouwer/pick-block-pro#15]
When I copy a glow_item_frame with an item, a normal item_frame is saved along with its contents.

_Version: Pick-Block-Pro-1.6.18_

![grafik](https://github.com/Sjouwer/pick-block-pro/assets/4140635/5dedb85e-cb20-48d7-9c62-771ac705a58b)

![grafik](https://github.com/Sjouwer/pick-block-pro/assets/4140635/0f35c40e-083f-47c6-baf8-16a2f523fd44)

**Comment by Sjouwer** [comment]
Thank you for the issue report.
The issue should be fixed now, a new release will be published for 1.19 and soon 1.20 once I've also implemented #14.
