### ISSUE TITLE
Does not copy the side of the stairs (for example)

### ISSUE THREAD

**Issue by arushenst** [Sjouwer/pick-block-pro#17]
Why? I try to do it but I can't

**Comment by Sjouwer** [comment]
You need to hold ALT while using pick block

**Comment by arushenst** [comment]
I know that the button needs to be hold, I do it, the fact is that it copies all the blocks, but there is no side of stairs

**Comment by Sjouwer** [comment]
I'm not entirely sure what you mean. Are you trying to copy the orientation of the side of the stairs? Are you also in creative mode?

**Comment by arushenst** [comment]
yes

**Comment by Sjouwer** [comment]
What happenens when you place the block down?

**Comment by arushenst** [comment]
nothing

**Comment by Sjouwer** [comment]
Does it say "+BlockState NBT" when you hover over the item inside the inventory?

**Comment by arushenst** [comment]
no
I am using the latest version fabric 1.20.1
I hold alt when I do this.

**Comment by Sjouwer** [comment]
Are you sure the mod is loaded? Do you have Mod Menu installed, does it show Pick Block Pro inside the mod list?

**Comment by arushenst** [comment]
I wanted to add this, yes, the mod is installed, it works with everything else except this one, mod on the list

**Comment by Sjouwer** [comment]
Stairs are one of the first things I test on every new mc version and they work perfectly fine for me:
![image](https://github.com/Sjouwer/pick-block-pro/assets/84018133/d93b9ff7-b604-4a0d-963d-d2f1a52d4f9e)
![image](https://github.com/Sjouwer/pick-block-pro/assets/84018133/d88cb157-34dc-4674-88fa-36ad0b07b122)
![image](https://github.com/Sjouwer/pick-block-pro/assets/84018133/292f361d-ecdd-4248-81a2-305ad29c9a1f)

**Comment by Sjouwer** [comment]
What else did you try that did actually work?

**Comment by arushenst** [comment]
oh my god.. i am now feeling cringe from myself and shame.. i pressed ctrl instead of alt literally all the time, confusing them and not noticing the difference.. I'm sorry that I wasted your time in my stupidity

**Comment by Sjouwer** [comment]
Ah lol, that's alright, that can happen. I'm happy to hear it's working correctly though :)
I'll close this now
