### ISSUE TITLE
Toolpick on Survival

### ISSUE THREAD

**Issue by peow** [Sjouwer/pick-block-pro#23]
when you are in survival and use the Tool Picker, it will pick up the best tool from your inventory, but for example if I have an iron pickaxe and also a diamond pickaxe, but the diamond pickaxe only has 1 durability, the Tool Picker will give me the diamond pickaxe, which ends up not being the best choice, it would be interesting if the Tool Picker ignored tools that are below 30 durability or something like this
![image](https://github.com/Sjouwer/pick-block-pro/assets/105888751/8eb95351-bdc9-402f-86e1-630626c089d2)

If you find this suggestion interesting and are going to put it in the mod, I ask you to update to fabric 1.20.1 with support for fabric loader 0.14.22

**Comment by Sjouwer** [comment]
Thanks for the suggestion, sounds like a good idea.
I'll try to add it very soon, probably will also add a config option to be able to adjust at which durability it'll skip a tool

**Comment by Sjouwer** [comment]
I've released a new version with your requested suggestion, sorry that it took so long:
https://modrinth.com/mod/pick-block-pro/version/1.7.25

**Comment by peow** [comment]
no worries, thanks
