### ISSUE TITLE
Survival pick range

### ISSUE THREAD

**Issue by SebSemos** [Sjouwer/pick-block-pro#25]
In the config you can change the range for picked things, but I play with an extended range effect on beacons in survival. So I think it should have an option that doesn't override range in this game mode.

**Comment by Sjouwer** [comment]
Yeah that sounds like a good idea with the new ability to change the interaction range, in the past that wasn't really a concern. I'll add a config option

**Comment by Sjouwer** [comment]
I've released a new version with your requested suggestion, sorry that it took so long:
**1.20 - 1.20.2:** https://modrinth.com/mod/pick-block-pro/version/1.7.27
**1.20.3 - 1.20.4:** https://modrinth.com/mod/pick-block-pro/version/1.8.27

**Comment by SebSemos** [comment]
No worries. That's cool :)
