### ISSUE TITLE
Not working with latest version of Quilt on multliplayer servers

### ISSUE THREAD

**Issue by AlphaCraft9658** [Sjouwer/pick-block-pro#26]
I don't know exactly what is happening, but whenever I try to pick an item, that's inside my inventory, when I'm on a multiplayer server, the item appears for a split second and then instantly disappears.

**Comment by Sjouwer** [comment]
Thank you for your report, however I can't seem to reproduce your issue.
Would you be able to provide me with the exact versions of everything you're using?
Minecraft, quilt, pbp, any other mods you might have etc

**Comment by AlphaCraft9658** [comment]
> Thank you for your report, however I can't seem to reproduce your issue. Would you be able to provide me with the exact versions of everything you're using? Minecraft, quilt, pbp, any other mods you might have etc

I'm using Minecraft 1.20.1 with Quilt 0.23.1.
Here is a mod list I exported:
Hope it's okay in this format and as plain-text.
- Indium [1.0.30+mc1.20.4]
- Smooth Swapping [0.9.3.1]
- BetterF3 [7.0.2]
- MidnightControls Extra [1.0.0]
- Debugify [1.20.1+2.0]
- Journeymap [5.9.18]
- Roughly Enough Items [12.0.684]
- Mod Menu [7.2.2]
- PipeBlocker [1.2.0]
- AppleSkin [2.5.1+mc1.20]
- Armor Chroma [1.2.6]
- Pick Block Pro [1.7.21]
- NotEnoughAnimations [1.7.0]
- Freecam [1.2.1+1.20]
- Sound Physics Remastered [1.20.1-1.3.1]
- Dynamic FPS [3.3.3]
- Effective [2.1.1+1.20.1]
- AdvancementInfo [1.20-fabric0.83.0-1.4]
- Craftify [1.14.0]
- No Chat Reports [1.20.1-v2.2.2]
- Dynamic Music [2.3.2+1.20]
- e4mc [4.0.1]
- ExtraSounds [2.3.1+1.19.2-1.19.1]
- Cosmetica [1.2.7]
- WorldEdit [7.2.15+6463-5ca4dff]
- AmbientSounds [5.3.8]
- Better Statistics Screen [3.8+fabric-1.20.1]
- Iris [1.6.17]
- Adaptive Tooltips [1.3.0]
- Fabric API [0.87.0+1.20.1]
- Blur (Fabric) [3.1.0]
- Status Effect Bars [1.0.3]
- Smooth Scrolling Refurbished [1.1.2]
- Chest Tracker [1.1.23]
- Sign Tools [1.0.3]
- Meteor Client [0.5.4-1935]
- Shulker Box Tooltip [4.0.4+1.20.1]
- Simple Voice Chat [1.20.1-2.5.1]
- essential-container [1.0.0]
- Ok Zoomer [5.0.1+1.20.1]
- 3d-Skin-Layers [1.6.2]
- Chat Heads [0.10.31]
- Replay Mod [1.20.1-2.6.14]
- Clumps [12.0.0.3]
- Memory Leak Fix [1.1.5]
- LambDynamicLights [2.3.2+1.20.1]
- Resourcify [1.3.1]
- DeftuLib [1.7.0]
- MidnightControls [1.7.4+1.19]
- Mouse Tweaks [2.25]
- Enhanced Block Entities [0.9+1.20]
- More Culling [1.20.4-0.22.1]
- CreativeCore [2.11.15]
- ExtraSounds [2.3.1+1.20.1~lonefelidae16-build.1]
- EntityCulling-Fabric [1.6.2-mc1.20.1]
- Nvidium [0.2.6-beta]
- Chunks Fade In [1.0.4-1.20.1]
- Elytra/Chestplate Swapper [1.3.0-MC1.20]
- Quilt Kotlin Libraries [2.1.3]
- Draggable Lists [1.0.1]
- Essential Dependencies [0]
- Architectury [9.1.12]
- Cloth Config v11 [11.1.118]
- FerriteCore [6.0.1]
- Quilted Fabric API [7.5.0+0.91.0-1.20.1]
- Screencapper [1.3.0]
- Falling Leaves [1.15.4]
- Too Many Players [1.20-1.1.5]
- Lithium [0.11.2]
- Continuity [3.0.0-beta.4+1.20.1]
- Inventory Profiles Next [1.10.9]
- MaLiLib [0.16.3]
- libIPN [4.0.1]
- Replanter [1.3]
- Presence Footsteps [1.9.1]
- YetAnotherConfigLib [3.2.1+1.20]
- ItemPhysicLite_FABRIC_v1.6.3_mc1.20.2
- ViaFabricPlus [2.8.7]
- Sodium [0.5.8+mc1.20.1]
- AntiGhost [1.20-fabric0.83.0-1.1.5]
- Fabric Language Kotlin [1.10.17+kotlin.1.9.22]
- Alternate Current [1.7.0]
- perspektive [1.3.3]
- Starlight [1.1.2+fabric.dbc156f]
- Eating Animation [1.20+1.9.5]
- Litematica [0.15.3]

**Comment by Sjouwer** [comment]
Could you see if this version resolves your issue?
https://modrinth.com/mod/pick-block-pro/version/1.7.25

**Comment by AlphaCraft9658** [comment]
> Could you see if this version resolves your issue?
> https://modrinth.com/mod/pick-block-pro/version/1.7.25

I will check once I'm home. I should be already up-to-date though.

**Comment by AlphaCraft9658** [comment]
> Could you see if this version resolves your issue? https://modrinth.com/mod/pick-block-pro/version/1.7.25

That version requires cloth-config v12 at least. Minecraft 1.20.1 doesn't have that.

**Comment by Sjouwer** [comment]
Ah shit, that's my bad, didn't think about that one.
Could you try the second file I just uploaded? (grey one)
![image](https://github.com/Sjouwer/pick-block-pro/assets/84018133/b0d514f3-a50e-4556-966a-b24985e41ec8)

**Comment by AlphaCraft9658** [comment]
> Ah shit, that's my bad, didn't think about that one.
> Could you try the second file I just uploaded? (grey one)
> ![image](https://github.com/Sjouwer/pick-block-pro/assets/84018133/b0d514f3-a50e-4556-966a-b24985e41ec8)
> 

I'll try tomorrow.

**Comment by AlphaCraft9658** [comment]
> Ah shit, that's my bad, didn't think about that one. Could you try the second file I just uploaded? (grey one) ![image](https://private-user-images.githubusercontent.com/84018133/309338355-b0d514f3-a50e-4556-966a-b24985e41ec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDE4NDIsIm5iZiI6MTcwOTQwMTU0MiwicGF0aCI6Ii84NDAxODEzMy8zMDkzMzgzNTUtYjBkNTE0ZjMtYTUwZS00NTU2LTk2NmEtYjI0OTg1ZTQxZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE3NDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MmU1YWU3YjU1MTE0YmExYWZkYmRmZTYyNzgzNDMyZGMyNjQ4MGM1MDkxMjBhZjNlMGU5NTdlOTkzNGRiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdW4XYfJw8Hd4Lpe_PxnEo-1WyciXY0zp6ziyBrkBfk)

Okay. That fixed my issue.

**Comment by Sjouwer** [comment]
Awesome, that's great to hear, thanks a lot for testing!
Sadly enough I can't seem to make the new file the primary file, so I probably need to do a reupload.
