### ISSUE TITLE
Copying a player's head does not copy the note_block_sound

### ISSUE THREAD

**Issue by Zailer43** [Sjouwer/pick-block-pro#27]
## Description
In version 1.20, Mojang added the `note_block_sound` to player heads, allowing for playing a sound when right-clicking on a note block underneath. However, since this tag is saved in `BlockEntityTag` and not in `SkullOwner`, it's not added by pick block pro

https://github.com/Sjouwer/pick-block-pro/blob/1.20.4/src/main/java/io/github/sjouwer/pickblockpro/util/NbtUtil.java#L93

## Original item:
```{SkullOwner: {Id: [I; 1881028098, 1895057075, -1197460482, -1593680102], Properties: {textures: [{Value: "eyJ0aW1lc3RhbXAiOjE3MTIyNjIzNDQyNDcsInByb2ZpbGVJZCI6IjcwMWUzNjAyNzBmNDQ2YjNiOGEwMzNmZWExMDI1ZjFhIiwicHJvZmlsZU5hbWUiOiJaYWlsZXI0MyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTM0YzAxY2FhNzgzNGVlY2RlYzJkZjU5MDc3MjgwMTU2MDE4ZWQxYmI5ZDE1ODNlZWUxZDU1N2VkYjM4MGRiMCJ9LCJDQVBFIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyJ9fX0="}]}, Name: "Zailer43"}, BlockEntityTag: {id: "minecraft:skull", note_block_sound: "minecraft:entity.villager.ambient"}}```

## Pick block pro item:
```{SkullOwner: {Id: [I; 1881028098, 1895057075, -1197460482, -1593680102], Properties: {textures: [{Value: "eyJ0aW1lc3RhbXAiOjE3MTIyNjIzNDQyNDcsInByb2ZpbGVJZCI6IjcwMWUzNjAyNzBmNDQ2YjNiOGEwMzNmZWExMDI1ZjFhIiwicHJvZmlsZU5hbWUiOiJaYWlsZXI0MyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTM0YzAxY2FhNzgzNGVlY2RlYzJkZjU5MDc3MjgwMTU2MDE4ZWQxYmI5ZDE1ODNlZWUxZDU1N2VkYjM4MGRiMCJ9LCJDQVBFIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyJ9fX0="}]}, Name: "Zailer43"}}```

## Details
minecraft = 1.20.4
pick_block_pro = 1.8.27
fabric_api = 0.96.11+1.20.4
cloth_config = 13.0.121

**Comment by Sjouwer** [comment]
Thank you for the report, I was unaware of this change.
Should be fixed now, will publish a new release soon.

Edit:
New release: https://modrinth.com/mod/pick-block-pro/version/1.8.28
