### ISSUE TITLE
"+BlockEntity Data" - use tooltip instead of lore

### ISSUE THREAD

**Issue by Daniel99j2** [Sjouwer/pick-block-pro#31]
With the new changes in 1.20.5, block entities copying the item's components, I would like to ask that instead of adding lore when picking a block, add a tooltip if the item has the block_entity_data. This is useful if you are picking a block, placing it, then later picking it again. Sometimes this causes the lore to be added repeatedly (try with a blank player head.)

[video](https://github.com/user-attachments/assets/c6eadf34-a09f-4fe2-9be7-3b327266b299)
![image](https://github.com/user-attachments/assets/82df55f2-8592-4667-8849-660faa5309d6)

**Comment by Sjouwer** [comment]
I've added a check to prevent adding lore lines that already exist on the item.
Further more, I've removed the lore line when coying a player head that only contains profile components.
This should pretty much be in line with how it used to be before the 1.20.5 update

**Comment by Daniel99j2** [comment]
Cool!
