### ISSUE TITLE
cannot see the ActiveEffects tag anymore when entity picking

### ISSUE THREAD

**Issue by tatatot234** [Sjouwer/pick-block-pro#33]
I am no longer able to see the mentioned nbt tag when copying.
I am certain that it worked a few months ago, reading the minecraft wiki they changed the tag's name from ActiveEffects to active_effects, but i couldnt make out if that is the reason why.

**Comment by Sjouwer** [comment]
Thank you for the report, I'll look into it soon

**Comment by Sjouwer** [comment]
I looked into it and sadly it seems like the active effects are only available server side and not client side. If it worked in the past then this probably changed with 1.20.5 where they overhauled the status effects. Since this mod is fully client side I sadly can't do anything about this :/
