### ISSUE TITLE
Suggestion: Overrides in Texture Packs

### ISSUE THREAD

**Issue by AlphaLeoli** [Sjouwer/pick-block-pro#34]
You would be able to define overrides for block picking in texture packs rather than in your config. That way you can:
1. stack packs
2. share these packs better
3. easily create overrides

**Comment by Sjouwer** [comment]
I'm sorry, however that's just now how texture packs work or are meant for.

**Comment by AlphaLeoli** [comment]
wdym it's not how they work i've seen many a mod do this
