### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by buiawpkgew1** [Sjouwer/pick-block-pro#7]
How to write in multiple languages, can you teach it?

**Comment by Sjouwer** [comment]
I assume you mean being able to have text translated?
You need to use `Text.Translatable()`
As for the config, that's being handled by Cloth Config (autoconfig).

You can find more info here:
https://fabricmc.net/wiki/tutorial:lang

Let me know if you still got some questions

**Comment by buiawpkgew1** [comment]
> I assume you mean being able to have text translated? You need to use `Text.Translatable()` As for the config translations, that's being handled by Cloth Config (autoconfig).
> 
> You can find more info here: [fabricmc.net/wiki/tutorial:lang](https://fabricmc.net/wiki/tutorial:lang)
> 
> Let me know if you still got some questions

i don't need the item

**Comment by Sjouwer** [comment]
Check the "Using custom translatable text" part of the wiki page

**Comment by Sjouwer** [comment]
Where is this from?
It's difficult to tell what `Setting` expects for you.
I can imagine it's something that already makes it translatable for you if you provide only a key

**Comment by buiawpkgew1** [comment]
> 这是从哪里来的？很难说出对你的期望。我可以想象，如果您只提供一个密钥，它已经可以为您翻译`Setting`

Only translate name and description
![image](https://user-images.githubusercontent.com/71136405/184368436-bfd6e4db-4eae-4065-bf6a-fc920cc10978.png)
The original picture

**Comment by Sjouwer** [comment]
`Setting` / `BoolSetting` is from meteor-client and not from Minecraft, it seems they didn't implement a way to make those settings translatable. There's sadly nothing you can do about that except rewriting those yourself

**Comment by Sjouwer** [comment]
I recommend making an issue about it on their github
