### ISSUE TITLE
[Suggestion] Add config option for disabling/enabling hotbar item id pasting in chat

### ISSUE THREAD

**Issue by JustLetterV** [Sjouwer/pick-block-pro#9]
Would be great to have configuration option for disabling/enabling [this](https://github.com/Sjouwer/pick-block-pro/blob/0f87a85be0406fbc3db71c6cef1d9ecf643f7d19/src/main/java/io/github/sjouwer/pickblockpro/mixin/KeyboardMixin.java#L21) feature.

**Why?**

If user doesn't need this feature, they would be able to disable it and wouldn't use it accidentally when trying to write characters "[" and "]" or other that can be written using ctrl+alt+number combo.

Thank you for reading and hopefully this is something that could possibly be added in future :)

**Comment by Sjouwer** [comment]
Thank you for the suggestion. My keyboard hasn't got a layout like that where ctrl is ever used together with the numbers, so didn't cross my mind to account for that. I'll add an option very soon!

**Comment by Sjouwer** [comment]
I've added a config option to fully disable this feature.
I also made sure that the hotbar picker only allows for CTRL + Number.
CTRL + ALT + Number no longer activates the hotbarpicker now.
Expect this to be released with 1.19.3
